name:  Scraper CI

on: [push, pull_request]

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: 15
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Build app
        run: |
          ./gradlew build --stacktrace
